Concesionario/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from concesionarioapp.views import Login
from concesionarioapp.views import Logout


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Login.as_view(), name='login'),
    url(r'^logout/', Logout.as_view(), name='logout'),
    url(r'^vendedores/', include('vendedores.urls', namespace='vendedores')),
    url(r'^compradores/', include('compradores.urls', namespace='compradores')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

compradores/urls.py
from django.conf.urls import url
from compradores.views import ListadoVehiculos
from compradores.views import ModificaPerfil
from compradores.views import VisualizaPerfilVendedor
from compradores.views import VisualizaVehiculo

urlpatterns = [
    url(r'^listar-vehiculos/', ListadoVehiculos.as_view(), name='listar_vehiculos'),
    url(r'^modificar-perfil/', ModificaPerfil.as_view(), name='modificar_perfil'),
    url(r'^perfil-vendedor/(?P<id_vendedor>\w+)', VisualizaPerfilVendedor.as_view(), name='visualizar_perfil_vendedor'),
    url(r'^visualizar-vehiculos/(?P<id_vehiculo>\w+)', VisualizaVehiculo.as_view(), name='visualizar_vehiculo'),
]

vendedores/urls.py
from django.conf.urls import url
from vendedores.views import ListadoVehiculos
from vendedores.views import AdicionaVehiculo
from vendedores.views import VisualizaVehiculo
from vendedores.views import BorraVehiculo
from vendedores.views import ModificaVehiculo
from vendedores.views import ModificaPerfil

urlpatterns = [
    url(r'^listar-vehiculos/', ListadoVehiculos.as_view(), name='listar_vehiculos'),
    url(r'^adicionar-vehiculos/', AdicionaVehiculo.as_view(), name='adicionar_vehiculo'),
    url(r'^visualizar-vehiculos/(?P<id_vehiculo>\w+)', VisualizaVehiculo.as_view(), name='visualizar_vehiculo'),
    url(r'^borrar-vehiculos/(?P<id_vehiculo>\w+)', BorraVehiculo.as_view(), name='borrar_vehiculo'),
    url(r'^modificar-vehiculos/(?P<id_vehiculo>\w+)', ModificaVehiculo.as_view(), name='modificar_vehiculo'),
    url(r'^modificar-perfil/', ModificaPerfil.as_view(), name='modificar_perfil'),
]

compradores/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

concesionarioapp/models.py
# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _
from django.db import models
from django.contrib.auth.models import User

class Categoria(models.Model):
    catid = models.AutoField(primary_key=True)
    catipo = models.CharField(max_length=50, blank=True, null=True)

    def __unicode__(self):
        return self.catipo

    class Meta:
        verbose_name_plural = "Categorias"
        verbose_name = "Categoria"


DOC_CHOICES = (
    ('CC', _(u"Cédula de Ciudadanía (CC)")),
    ('TI', _(u"Tarjeta de Identidad (TI)")),
    ('RC', _(u"Registro Civil (RC)")),
    ('CE', _(u"Cédula de Extranjería (CE)")),
    ('CI', _(u"Carné de Identidad (CI)")),
    ('DNI', _(u"Documento Nacional de Identidad (DNI)")),
    ('DUI', _(u"Documento Único de Identidad (DUI)"))
)

class DatosPersonales(models.Model):
    datid = models.AutoField(primary_key=True)
    datnombre = models.CharField(max_length=50)
    datapellido = models.CharField(max_length=50, blank=True, null=True)
    datipoid = models.CharField(max_length=20, blank=True, null=True, choices=DOC_CHOICES, default='CC')
    datnumeroid = models.CharField(max_length=20, blank=True, null=True)
    datelefono = models.CharField(max_length=20, blank=True, null=True)
    datcorreo = models.CharField(max_length=50, blank=True, null=True)
    foto = models.ImageField(upload_to='usuarios', default='usuarios/usuario.png')
    usuid = models.OneToOneField(User)

    def __unicode__(self): # def __str__(self):
        return "%s %s" % (self.datnombre, self.datapellido)

    class Meta:
        verbose_name_plural = "Datos Personales"
        verbose_name = "Datos Persona"

class Rol(models.Model):
    rolid = models.AutoField(primary_key=True)
    roltipo = models.CharField(max_length=50)

    def __unicode__(self): # def __str__(self):
        return self.roltipo

    class Meta:
        verbose_name_plural = "Roles"
        verbose_name = "Rol"

class UsuarioRol(models.Model):
    rolid = models.ForeignKey(Rol)
    usuid = models.ForeignKey(User)

    def __unicode__(self): # def __str__(self):
        return "%s-%s" % (self.rolid.roltipo, self.usuid.username)

    class Meta:
        verbose_name_plural = "Roles Usuarios"
        verbose_name = "Rol Usuario"


class Vehiculo(models.Model):
    vehplaca = models.CharField(primary_key=True, max_length=10)
    catid = models.ForeignKey(Categoria)
    vehmodelo = models.IntegerField()
    vehmarca = models.CharField(max_length=50)
    vehestado = models.CharField(max_length=30, blank=True, null=True)
    vehprecio = models.IntegerField()
    vehfoto = models.ImageField(upload_to='vehiculos', default='vehiculos/vehiculo.png')
    datid = models.ForeignKey(DatosPersonales)

    def __unicode__(self): # def __str__(self):
        return "%s-%s" % (self.vehplaca, self.vehmarca)

    class Meta:
        verbose_name_plural = "Vehiculos"
        verbose_name = "Vehiculo"

compradores/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.views.generic.base import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from concesionarioapp.models import DatosPersonales
from concesionarioapp.models import Vehiculo

from concesionarioapp.forms import VehiculoForm
from concesionarioapp.forms import DatosPersonalesForm


class ListadoVehiculos(LoginRequiredMixin, View):
    login_url = '/'
    template_name = 'compradores/listar_vehiculos.html'

    def get(self, request):
        try:
            datos_usuario = DatosPersonales.objects.get(usuid=request.user.pk)
            lista_vehiculos = Vehiculo.objects.all()
            return render(request,
                          self.template_name,
                          {'vehiculos': lista_vehiculos,
                           'foto_usuario': datos_usuario.foto})

        except DatosPersonales.DoesNotExist:
            return render(request, "pages-404.html")


class ModificaPerfil(LoginRequiredMixin, View):
    login_url = '/'
    form_class = DatosPersonalesForm
    template_name = 'compradores/perfil_comprador.html'

    def get(self, request):
        try:
            datos_usuario = DatosPersonales.objects.get(usuid=request.user.pk)
            form = self.form_class(request.user, instance=datos_usuario)
            return render(request,
                          self.template_name,
                          {'form': form,
                           'foto_usuario': datos_usuario.foto})

        except DatosPersonales.DoesNotExist:
            return render(request, "pages-404.html")

    def post(self, request):
        try:
            datos_usuario = DatosPersonales.objects.get(usuid=request.user.pk)
            form = self.form_class(request.user, request.POST, request.FILES, instance=datos_usuario)

            if form.is_valid():
                form.save()
                messages.add_message(request, messages.INFO, 'El Perfil se modificó correctamente')

            else:
                messages.add_message(request, messages.ERROR, 'El Perfil no se pudo modificar')

            return self.get(request)

        except DatosPersonales.DoesNotExist:
            return render(request, "pages-404.html")


class VisualizaPerfilVendedor(LoginRequiredMixin, View):
    login_url = '/'
    form_class = DatosPersonalesForm
    template_name = 'compradores/perfil_vendedor.html'

    def get(self, request, id_vendedor):
        try:
            datos_usuario = DatosPersonales.objects.get(usuid=id_vendedor)
            form = self.form_class(request.user, instance=datos_usuario)
            return render(request,
                          self.template_name,
                          {'form': form,
                           'foto_usuario': datos_usuario.foto})

        except DatosPersonales.DoesNotExist:
            return render(request, "pages-404.html")


class VisualizaVehiculo(LoginRequiredMixin, View):
    login_url = '/'
    form_class = VehiculoForm
    template_name = 'compradores/visualizar_vehiculo.html'

    def get(self, request, id_vehiculo):
        try:
            datos_usuario = DatosPersonales.objects.get(usuid=request.user.pk)
            vehiculo = Vehiculo.objects.get(vehplaca=id_vehiculo)
            form = self.form_class(datos_usuario, instance=vehiculo)
            return render(request,
                          self.template_name,
                          {'form': form,
                           'foto_vehiculo': vehiculo.vehfoto,
                           'foto_usuario': datos_usuario.foto})

        except DatosPersonales.DoesNotExist:
            return render(request, "pages-404.html")

        except Vehiculo.DoesNotExist:
            return render(request, "pages-404.html")

compradores/templates/compradores/alerts.html
{%  load static %}
<link rel="stylesheet" type="text/css" href="{% static 'stylesheets/sweetalert.css' %}">
<script src="{% static 'javascripts/jquery.js' %}"></script>
<script src="{% static 'javascripts/sweetalert.min.js' %}"></script>

<div id="alerts">
    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <script>
                    $(document).ready(function ()
                    {
                        swal(
                        {
                            type: "error",
                            title: "ERROR",
                            text: "{{ message }}",
                            showConfirmButton: true
                        });
                    })
                </script>

            {% else %}
                <script>
                    $(document).ready(function ()
                    {
                        swal(
                        {
                            type: "success",
                            title: "INFORMACIÓN",
                            text: "{{ message }}",
                            showConfirmButton: true
                        });
                    })
                </script>
            {% endif %}
        {% endfor %}
    {% endif %}
</div>

compradores/templates/compradores/base_compradores.html
{% load static %}

<!DOCTYPE html>
    <!--[if IE 8]>         <html class="ie8"> <![endif]-->
    <!--[if IE 9]>         <html class="ie9 gt-ie8"> <![endif]-->
    <!--[if gt IE 9]><!--> <html class="gt-ie8 gt-ie9 not-ie"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Concesionario</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
        <!-- Open Sans font from Google CDN -->
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300&subset=latin" rel="stylesheet" type="text/css">
        <!-- Pixel Admin's stylesheets -->
        <link href="{% static 'stylesheets/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'stylesheets/pixel-admin.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'stylesheets/widgets.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'stylesheets/pages.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'stylesheets/rtl.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'stylesheets/themes.min.css' %}" rel="stylesheet" type="text/css">

        {% block styles %}
        {% endblock %}

        <!--[if lt IE 9]>
            <script src="{% static 'javascripts/ie.min.js' %}"></script>
        <![endif]-->
    </head>

    <body class="theme-adminflare main-menu-animated">
        <div id="main-wrapper">
            <div id="main-navbar" class="navbar navbar-inverse" role="navigation">
                <!-- Main menu toggle -->
                <button type="button" id="main-menu-toggle"><i class="navbar-icon fa fa-bars icon"></i><span class="hide-menu-text">HIDE MENU</span></button>

                <div class="navbar-inner">
                    <!-- Main navbar header -->
                    <div class="navbar-header">

                        <!-- Logo -->
                        <a href="{% url 'logout' %}" class="navbar-brand">
                            <div><img alt="Pixel Admin" src="{% static 'images/pixel-admin/main-navbar-logo.png'%}"></div>
                            Concesionario
                        </a>

                        <!-- Main navbar toggle -->
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapse"><i class="navbar-icon fa fa-bars"></i></button>

                    </div> <!-- / .navbar-header -->

                    <div id="main-navbar-collapse" class="collapse navbar-collapse main-navbar-collapse">
                        <div>
                            <div class="right clearfix">
                                <ul class="nav navbar-nav pull-right right-navbar-nav">
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle user-menu" data-toggle="dropdown">
                                            <img src="{{ foto_usuario.url }}" id="img_usuario" alt="Foto Usuario">
                                            <span>{{ user.first_name }}&nbsp;{{ user.last_name }}</span>
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a href="{% url 'compradores:modificar_perfil' %}">
                                                    <i class="dropdown-icon fa fa-user"></i>&nbsp;&nbsp;Perfil
                                                </a>
                                            </li>
                                            <li class="divider"></li>
                                            <li>
                                                <a href="{% url 'logout' %}">
                                                    <i class="dropdown-icon fa fa-power-off"></i>&nbsp;&nbsp;Cerrar Sesión
                                                </a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul> <!-- / .navbar-nav -->
                            </div> <!-- / .right -->
                        </div>
                    </div> <!-- / #main-navbar-collapse -->
                </div> <!-- / .navbar-inner -->
            </div> <!-- / #main-navbar -->
        <!-- /2. $END_MAIN_NAVIGATION -->
            <div id="main-menu" role="navigation">
                <div id="main-menu-inner">
                    <div class="menu-content top" id="menu-content-demo">
                        <div>
                            <div class="text-bg">
                                <span class="text-slim">Bienvenido,</span><br>
                                <span class="text-semibold">{{ user.first_name }}</span>
                            </div>
                            <img src="{{ foto_usuario.url }}" id="img_usuario" alt="Foto Usuario">
                            <a href="#" class="close">&times;</a>
                        </div>
                    </div>
                    <ul class="navigation">
                        <li class="mm-dropdown" id="item_vehiculos">
                            <a href="#">
                                <i class="menu-icon fa fa-eye"></i>
                                <span class="mm-text">Buscar</span>
                            </a>
                            <ul>
                                <li id="buscar_vehiculo">
                                    <a tabindex="-1" href="{% url 'compradores:listar_vehiculos' %}">
                                        <i class="menu-icon fa fa-eye"></i>
                                        <span class="mm-text">Vehículo</span>
                                    </a>
                                </li>
                                <li>
                                    <a tabindex="-1" href="">
                                        <i class="menu-icon fa fa-eye"></i>
                                        <span class="mm-text">Rango Precio</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li id="item_usuario">
                            <a href="{% url 'compradores:modificar_perfil' %}">
                                <i class="menu-icon fa fa-user"></i>
                                <span class="mm-text">Perfil</span>
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'logout' %}">
                                <i class="menu-icon fa fa-power-off"></i>
                                <span class="mm-text">Cerrar Sesion</span>
                            </a>
                        </li>
                    </ul> <!-- / .navigation -->
                </div> <!-- / #main-menu-inner -->
            </div> <!-- / #main-menu -->
        <!-- /4. $MAIN_MENU -->
            <div id="content-wrapper">

                {% block content %}
                {% endblock %}

            </div> <!-- / #content-wrapper -->
            <div id="main-menu-bg"></div>
        </div> <!-- / #main-wrapper -->
        <!-- Get jQuery from Google CDN -->
        <!--[if !IE]> -->
            <script type="text/javascript"> window.jQuery || document.write('<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js">'+"<"+"/script>"); </script>
        <!-- <![endif]-->
        <!--[if lte IE 9]>
            <script type="text/javascript"> window.jQuery || document.write('<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js">'+"<"+"/script>"); </script>
        <![endif]-->
        <!-- Pixel Admin's javascripts -->
        <script src="{% static 'javascripts/bootstrap.min.js' %}"></script>
        <script src="{% static 'javascripts/pixel-admin.min.js' %}"></script>
        <script>var init = [];</script>
        <script type="text/javascript">
            init.push(function () {});
            window.PixelAdmin.start(init);
        </script>
        {% block scripts %}
        {% endblock %}

    </body>
</html>

compradores/templates/compradores/listar_vehiculos.html
{% extends 'compradores/base_compradores.html' %}

{% block styles %}
{% endblock %}

{% block content %}
    {% include 'compradores/alerts.html' %}
    <div class="page-header">
        <div class="row">
            <!-- Page header, center on small screens -->
            <h1 class="col-xs-12 col-sm-4 text-center text-left-sm">
                <i class="fa fa-edit page-header-icon"></i>&nbsp;&nbsp;Consulta de Vehiculos
            </h1>
            <div class="col-xs-12 col-sm-8">
                <div class="row">
                    <hr class="visible-xs no-grid-gutter-h">
                    <!-- Margin -->
                    <div class="visible-xs clearfix form-group-margin"></div>
                    <!-- Search field -->
                </div>
            </div>
        </div>
    </div> <!-- / .page-header -->
    <!-- / Javascript -->
    <div class="panel">
        <div class="panel-body">
            <div class="table-primary">
                <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="jq-datatables-example">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Placa</th>
                            <th>Modelo</th>
                            <th>Marca</th>
                            <th>Categoría</th>
                            <th>Precio</th>
                            <th>Vendedor</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for vehiculo in vehiculos %}
                        <tr class="odd gradeX">
                            <td>{{ forloop.counter }}</td>
                            <td>{{ vehiculo.vehplaca }}</td>
                            <td>{{ vehiculo.vehmodelo }}</td>
                            <td>{{ vehiculo.vehmarca }}</td>
                            <td>{{ vehiculo.catid.catipo }}</td>
                            <td>{{ vehiculo.vehprecio }}</td>
                            <td>
                                <a href="{% url 'compradores:visualizar_perfil_vendedor' vehiculo.datid.usuid.pk %}">{{ vehiculo.datid.datnombre }}&nbsp;{{ vehiculo.datid.datapellido }}</a>
                            </td>
                            <td>
                                <div class="btn-group" >
{#                                    <a href="{% url 'compradores:visualizar_vehiculo' vehiculo.vehplaca %}" class="btn btn-primary">Visualizar</a>#}
                                    <a href="{% url  'compradores:visualizar_vehiculo' vehiculo.vehplaca %}" class="btn btn-primary">Visualizar</a>
                                </div>&nbsp;
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        init.push(function ()
        {
            $('#jq-datatables-example').dataTable();
            $('#jq-datatables-example_wrapper .table-caption').text('Listado de Vehículos');
            $('#jq-datatables-example_wrapper .dataTables_filter input').attr('placeholder', 'Buscar...');
        });
    </script>
{% endblock %}

compradores/templates/compradores/perfil_comprador.html
{% extends 'compradores/base_compradores.html' %}
{% load static %}
{% block styles %}
{% endblock %}

{% block content %}
    {% include 'compradores/alerts.html' %}
    <div class="page-header">
        <div class="row">
            <h1 class="col-xs-12 col-sm-4 text-center text-left-sm">
                <i class="fa fa-edit page-header-icon"></i>
                &nbsp;&nbsp;Perfil Comprador
            </h1>
        </div>
    </div>
    <div class="profile-full-name">
        <span class="text-semibold">
            <i class="fa fa-edit page-header-icon"></i>&nbsp;Datos Comprador
        </span>
    </div>
    <div class="profile-row">
        <div class="left-col">
            <div class="profile-block">
                <div class="panel profile-photo">
                    <img src="{{ foto_usuario.url }}" id="img_usuario" alt="Foto Usuario">
                </div>
            </div>
        </div>
        <div class="right-col">
            <hr class="profile-content-hr no-grid-gutter-h">
            <div class="profile-content">
                <div class="panel">
                    <br><br>
                    <form method="post" id="form_usuario" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.errors }}
                                <label for="jq-validation-url" class="col-sm-3 control-label">
                                    <strong>{{ field.label }}</strong>
                                </label>
                                <div class="col-sm-9">
                                    {{ field }}
                                </div>
                            </div>
                        {% endfor %}
                        <br>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-9">
                                <button type="submit" class="btn btn-primary">Modificar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        init.push(function ()
        {
            $('body').addClass("page-profile");
            $('#item_usuario').addClass("active");
            $('#id_foto').pixelFileInput({ placeholder: 'Seleccione una imagen de perfil para el comprador'});
        });

        window.PixelAdmin.start(init);
    </script>

    {% block scripts_crud %}
    {% endblock %}
{% endblock %}

compradores/templates/compradores/perfil_vendedor.html
{% extends 'compradores/base_compradores.html' %}
{% load static %}
{% block styles %}
{% endblock %}

{% block content %}
    {% include 'compradores/alerts.html' %}
    <div class="page-header">
        <div class="row">
            <h1 class="col-xs-12 col-sm-4 text-center text-left-sm">
                <i class="fa fa-edit page-header-icon"></i>
                &nbsp;&nbsp;Perfil Vendedor
            </h1>
        </div>
    </div>
    <div class="profile-full-name">
        <span class="text-semibold">
            <i class="fa fa-edit page-header-icon"></i>&nbsp;Datos Vendedor
        </span>
    </div>
    <div class="profile-row">
        <div class="left-col">
            <div class="profile-block">
                <div class="panel profile-photo">
                    <img src="{{ foto_usuario.url }}" id="img_usuario" alt="Foto Usuario">
                </div>
            </div>
        </div>
        <div class="right-col">
            <hr class="profile-content-hr no-grid-gutter-h">
            <div class="profile-content">
                <div class="panel">
                    <br><br>
                    <form id="form_vendedor">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.errors }}
                                <label for="jq-validation-url" class="col-sm-3 control-label">
                                    <strong>{{ field.label }}</strong>
                                </label>
                                <div class="col-sm-9">
                                    {{ field }}
                                </div>
                            </div>
                        {% endfor %}
                        <br>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-9">
                                <a href="{% url 'compradores:listar_vehiculos' %}">
                                    <button type="button" class="btn btn-danger">Salir</button>
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        init.push(function ()
        {
            $('body').addClass("page-profile");
            $('#buscar_vehiculo').addClass("active");
         });

        window.PixelAdmin.start(init);


        $('#form_vendedor').find("input[type='text'], input[type='number'], input[type='file'], select, textarea").each(function (index, element)
        {
            $(element).prop('readonly', true);
            $(element).prop('disabled', true);
        });

        $('#form_vendedor').find("select").each(function (index, element)
        {
            $(element).attr('style', 'pointer-events: none;');
        });
    </script>

    {% block scripts_crud %}
    {% endblock %}
{% endblock %}

compradores/templates/compradores/visualizar_vehiculo.html
{% extends 'compradores/base_compradores.html' %}
{% load static %}
{% block styles %}
{% endblock %}

{% block content %}
    <div class="page-header">
        <div class="row">
            <h1 class="col-xs-12 col-sm-4 text-center text-left-sm">
                <i class="fa fa-edit page-header-icon"></i>
                &nbsp;&nbsp;Vehículo
            </h1>
        </div>
    </div>
    <div class="profile-full-name">
        <span class="text-semibold">
            <i class="fa fa-eye page-header-icon"></i>&nbsp;Visualizar Vehículo
        </span>
    </div>
    <div class="profile-row">
        <div class="left-col">
            <div class="profile-block">
                <div class="panel profile-photo">
                {% if foto_vehiculo.url %}
                    <img src="{{ foto_vehiculo.url }}" id="img_vehiculo" alt="Foto Vehiculo">
                {% else %}
                    <img src="{% static 'images/vehiculo.png' %}" id="img_vehiculo" alt="Foto Vehiculo">
                {% endif %}
                </div>
            </div>
        </div>
        <div class="right-col">
            <hr class="profile-content-hr no-grid-gutter-h">
            <div class="profile-content">
                <div class="panel">
                    <br><br>
                    <form id="form_vehiculo">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.errors }}
                                <label for="jq-validation-url" class="col-sm-3 control-label">
                                    <strong>{{ field.label }}</strong>
                                </label>
                                <div class="col-sm-9">
                                    {{ field }}
                                </div>
                            </div>
                        {% endfor %}
                        <br>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-9">
                                <a href="{% url 'compradores:listar_vehiculos' %}">
                                    <button type="button" class="btn btn-danger">Salir</button>
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        init.push(function ()
        {
            $('body').addClass("page-profile");
            $('#buscar_vehiculo').addClass("active");
        });

        window.PixelAdmin.start(init);

        $('#form_vehiculo').find("input[type='text'], input[type='number'], input[type='file'], select, textarea").each(function (index, element)
        {
            $(element).prop('readonly', true);
            $(element).prop('disabled', true);
        });

        $('#form_vehiculo').find("select").each(function (index, element)
        {
            $(element).attr('style', 'pointer-events: none;');
        });
    </script>

    {% block scripts_crud %}
    {% endblock %}
{% endblock %}